spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:

  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

  sql:
    init:
      mode: never   # чтобы не конфликтовать с Flyway

  flyway:
    enabled: true
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    user: sa
    password:
    locations: classpath:db/migration/h2

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  main:
    web-application-type: reactive

  data:
    redis:
      port: 6379   # общий порт

server:
  port: 8080

app:
  cache:
    ttl-seconds: 180
    prefix: "catalog:"

payment:
  base-url: http://localhost:8081