spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  sql:
    init:
      mode: always

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  main:
    web-application-type: reactive

  redis:
    host: redis
    port: 6379

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

server:
  port: 8080