-- Товары/заказы
CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description VARCHAR(1000),
    img_path VARCHAR(255),
    price DOUBLE,
    count INT
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_sum DOUBLE
);

CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT,
    item_id BIGINT,
    title VARCHAR(255),
    description VARCHAR(1000),
    img_path VARCHAR(255),
    price DOUBLE,
    count INT
);

-- Пользователи/роли
CREATE TABLE IF NOT EXISTS app_user (
  id UUID PRIMARY KEY,
  username VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(200) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS user_authority (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  authority VARCHAR(100) NOT NULL,
  CONSTRAINT fk_user_authority_user
    FOREIGN KEY(user_id) REFERENCES app_user(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_user_authority_user ON user_authority(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_user_authority_user_role
  ON user_authority(user_id, authority);